crm_campaign/tealcrm/lead/urls.py
from django.urls import path


from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert', views.ConvertToClientView.as_view(), name='convert'),
    path('add/',views.LeadCreateView.as_view(), name = 'add'),
    path('<int:pk>/add-comment/',views.AddCommentView.as_view(), name= 'add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(),name = 'add_file') ,
    path('api', views.ListCreateLeadView.as_view()),
    path('api/<int:pk>', views.UpdateDeleteLeadView.as_view()),
] 

crm_campaign/tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index,about
from userprofile.views import signup
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from userprofile.form import LoginForm 

from django.conf import settings
from django.conf.urls.static import static




# Define your LoginView with a template_name attribute
class CustomLoginView(LoginView):
    template_name = 'userprofile/login.html'
class CustomLogoutView(LogoutView):
    template_name = ''

urlpatterns = [
    path('',index, name='index'),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/teams/',include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/',about, name='about'),
    path('log-in/', CustomLoginView.as_view(authentication_form =LoginForm), name='login'),
    path('log-out' ,CustomLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),    
    path("__debug__/", include("debug_toolbar.urls")),
    path('dynfilters/', include('dynfilters.urls')),    
    path('campaign/', include('campaigns.urls')),
    path('templates/', include('templates.urls', namespace='templates')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_campaign/tealcrm/lead/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team
from product.models import Product
# Create your models here.

class LeadSource(models.Model):
    name = models.CharField(max_length=100, blank=True, null= True)
    description = models.CharField(max_length=200, blank=True, null= True)

    def __str__(self):
        return self.name
      
    class Meta:
        ordering = ('name',)
    

class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High')
    )
    NEW = 'new'
    CONTACTED = 'contacted'
    QUA = 'qualified'
    UNACTIONED = 'unactioned'
    UN = 'unqualified'
    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (QUA, 'Qualified'),
        (UN, 'Unqualified'),
        (UNACTIONED, 'Unactioned'),
    )
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=20, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE,default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    phone = models.CharField(max_length=20, blank=True, null= True)
    product_line = models.ForeignKey(Product, related_name='leads', on_delete=models.CASCADE,default=1)
    company = models.CharField(max_length=100, blank=True, null= True)
    job = models.CharField(max_length=100, blank=True, null= True)
    lead_source = models.ForeignKey(LeadSource,related_name='leads', on_delete=models.CASCADE,default=1)
    
    # @property
    # def full_name(self):
    #     return f"{self.first_name} {self.last_name}"

    # def  __str__(self):
    #     return self.full_name

    def __str__(self):
        return self.name
      
    class Meta:
        ordering = ('name',)
        # # Định nghĩa constraints
        # constraints = [
        #     models.CheckConstraint(
        #         name="valid_proprity",
        #         check=models.Q(Proprity__in=[choice[0] for choice in PRIORITY_CHOICES]),
        #     ),
        # ]


        # constraints = [
        #     models.CheckConstraint(
        #         name="valid_status",
        #         check=models.Q(Status__in=[choice[0] for choice in STATUS_CHOICES]),
        #     ),
        # ]

    

class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name= 'files', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='leadfiles')

    def __str__(self):
        return self.created_by.username
    
    

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name= 'comments', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField(null=True)

    def __str__(self):
        return self.created_by.username


    

crm_campaign/tealcrm/lead/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView, View
from .models import Lead
from client.models import Client, Comment as ClientComment
from team.models import Team
from .form import AddCommentForm, AddFileForm, AddLeadForm

from django.core.mail import send_mail

from django.core.mail import send_mass_mail

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.shortcuts import render


class LeadListView(LoginRequiredMixin, ListView):
    model = Lead
    paginate_by = 20  # Số lượng mục trên mỗi trang
    template_name = 'lead/lead_list.html'  # Thay 'your_template.html' bằng tên thực của template bạn muốn sử dụng

    def get_queryset(self):
        # Lọc queryset dựa trên người dùng đăng nhập và trạng thái chưa chuyển đổi
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user, converted_to_client=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Lấy queryset đã lọc
        queryset = self.get_queryset().order_by('-created_at')

        # Phân trang cho queryset đã lọc
        paginator = Paginator(queryset, self.paginate_by)

        # Lấy số trang hiện tại từ tham số GET trong request
        page_number = self.request.GET.get('page')

        try:
            # Lấy các đối tượng trên trang được chỉ định
            leads = paginator.page(page_number)
        except PageNotAnInteger:
            # Nếu page_number không phải là số nguyên, trả về trang đầu tiên
            leads = paginator.page(1)
        except EmptyPage:
            # Nếu trang không tồn tại (vd: page = 9999), trả về trang cuối cùng
            leads = paginator.page(paginator.num_pages)

        # Đưa queryset phân trang vào context
        context['object_list'] = leads
        return context
    def get_queryset(self):
        # Lọc queryset dựa trên người dùng đăng nhập và trạng thái chưa chuyển đổi
        queryset = super().get_queryset()
        queryset = queryset.filter(created_by=self.request.user, converted_to_client=False)

        # Tìm kiếm nếu có từ khóa
        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(email__icontains=search_query) |
                Q(status__icontains=search_query)
                # Thêm các trường bạn muốn tìm kiếm ở đây
            )

        return queryset



class LeadDetailView(LoginRequiredMixin,DetailView):
    model = Lead
    
    def get_context_data(self, **kwarg):
        context = super().get_context_data(**kwarg)
        context['form'] = AddCommentForm()
        context['fileform'] = AddFileForm()

        return context
    
    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk = self.kwargs.get('pk'))
    

class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')

    
    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk = self.kwargs.get('pk'))
    

    
class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    # fields = ('name', 'email', 'description','phone', 'priority', 'status', 'product_line', 'company','job')
    form_class = AddLeadForm
    success_url = reverse_lazy('leads:list')

    
    def get_context_data(self, **kwarg):
        context = super().get_context_data(**kwarg)
        context['title'] = 'Edit lead'
        return context

    
    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk = self.kwargs.get('pk'))
    
    


class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    #fields = ('name', 'email', 'description', 'phone', 'priority', 'status', 'product_line', 'company','job')
    form_class = AddLeadForm
    success_url = reverse_lazy('leads:list')

    # send_mail("It works!", "This will get sent through Sendinblue",
    #        "Bảo Lâm <baolam.main@gmail.com>", ["nguyenngocbaolamcva2020@gmail.com"])


    def get_context_data(self, **kwarg):
        context = super().get_context_data(**kwarg)
        team = self.request.user.userprofile.active_team
        context['team'] = team
        context['title'] = 'Add lead'

        return context
    
    def get_queryset(self):
        queryset = super(LeadCreateView, self).get_queryset()
        return queryset.filter(created_by=self.request.user)
    
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        team = self.request.user.userprofile.active_team
        self.object.created_by = self.request.user
        self.object.team = team
        self.object.save()

        return redirect(self.get_success_url())
    

class AddFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            team = self.request.user.userprofile.active_team
            file = form.save(commit=False)
            file.team = team
            file.lead_id = pk 
            file.created_by = request.user
            file.save()
            
        return redirect('leads:detail', pk=pk)
            
    

class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        
        form = AddCommentForm(request.POST)

        if  form.is_valid():
            team = self.request.user.userprofile.active_team
            comment = form.save(commit=False)
            comment.team = team 
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)




class ConvertToClientView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = self.request.user.userprofile.active_team

        client = Client.objects.create(
        name = lead.name,
        email = lead.email,
        description = lead.description,
        created_by= request.user,
        team=team,
        phone=lead.phone,
        company=lead.company,
        job=lead.job,
        product_line=lead.product_line,

        )
        lead.converted_to_client = True
        lead.save()
        
        #convert lead comment to client  comment
        comments = lead.comments.all()
        for comment in comments:
            ClientComment.objects.create(
                client = client,
                content = comment.content,
                created_by  =  comment.created_by,
                team = team,
            )
        
        messages.success(request, 'The lead was converted to a client.')

        return redirect('leads:list')




# Xử lý API dữ liệu

from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from rest_framework import status
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView


from lead.serializers import LeadSerializer
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError

class ListCreateLeadView(ListCreateAPIView):
    model = Lead
    serializer_class = LeadSerializer

    def get_queryset(self):
        return Lead.objects.all()

    def create(self, request, *args, **kwargs):
        email = request.data.get('email')
        
        # Kiểm tra định dạng email
        validator = EmailValidator()
        try:
            validator(email)
        except ValidationError as e:
            return JsonResponse({
                'message': 'Invalid email format!'
            }, status=status.HTTP_400_BAD_REQUEST)

        existing_lead = Lead.objects.filter(email=email).first()

        if existing_lead:
            serializer = LeadSerializer(existing_lead, data=request.data, partial=True)
        else:
            serializer = LeadSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()

            return JsonResponse({
                'message': 'Create a new Lead successful!'
            }, status=status.HTTP_201_CREATED)

        return JsonResponse({
            'message': 'Create a new Lead unsuccessful!'
        }, status=status.HTTP_400_BAD_REQUEST)
    

class UpdateDeleteLeadView(RetrieveUpdateDestroyAPIView):
    model = Lead
    serializer_class = LeadSerializer

    def put(self, request, *args, **kwargs):
        lead_instance = get_object_or_404(Lead, id=kwargs.get('pk'))
        serializer = LeadSerializer(lead_instance, data=request.data)

        if serializer.is_valid():
            serializer.save()

            return JsonResponse({
                'message': 'Update Car successful!'
            }, status=status.HTTP_200_OK)

        return JsonResponse({
            'message': 'Update Car unsuccessful!'
        }, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, *args, **kwargs):
        lead_instance = get_object_or_404(Lead, id=kwargs.get('pk'))
        lead_instance.delete()

        return JsonResponse({
            'message': 'Delete Car successful!'
        }, status=status.HTTP_200_OK)

        

crm_campaign/tealcrm/lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">{{ lead.name }}</h1>
    {% if lead.description %}
        <p>{{ lead.description }}</p>
    {% endif %}
    <style>
        .two-column-layout {
            display: grid;
            grid-template-columns: 1fr 1fr; /* Chia layout thành 2 cột bằng nhau */
            gap: 20px; /* Khoảng cách giữa các cột */

            
        }
        .two-column-layout div p {
        border-bottom: 1px solid #ccc; /* Dòng kẻ màu xám */
        padding-bottom: 8px; /* Khoảng cách từ chân dòng đến dòng kẻ */
        margin-bottom: 8px; /* Khoảng cách giữa các dòng */
    }
    </style>
    
    <div class="two-column-layout">
        <div>
            <h1 class="font-semibold">Priority</h1>
            <p class="mb-2">{{ lead.get_priority_display }}</p>
            <h1 class="font-semibold">Status</h1>
            <p class="mb-2">{{ lead.get_status_display }}</p>
            <h1 class="font-semibold">Create at</h1>
            <p class="mb-2">{{ lead.created_at }}</p>
            <h1 class="font-semibold">Modified at</h1>
            <p class="mb-6">{{ lead.modified_at }}</p>
            <h1 class="font-semibold">Lead Source</h1>
            <p class="mb-6">{{ lead.lead_source }}</p>
        </div>
        <div>
            <h1 class="font-semibold">Email</h1>
            <p class="mb-6">{{ lead.email }}</p>
            <h1 class="font-semibold">Phone</h1>
            <p class="mb-6">{{ lead.phone }}</p>
            <h1 class="font-semibold">Service</h1>
            <p class="mb-6">{{ lead.product_line }}</p>
            <h1 class="font-semibold">Company</h1>
            <p class="mb-6">{{ lead.company }}</p>
            <h1 class="font-semibold">Job</h1>
            <p class="mb-6">{{ lead.job }}</p>
        </div>
    </div>
  

    <hr class="my-4">
    <form id="lead_delete_form" method="post" action="{% url 'leads:delete' lead.id %}">
        {% csrf_token %}
    </form>

    <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-6 rounded-xl bg-blue-500 text-white">Convert to client</a>
    <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-6 rounded-xl bg-blue-500 text-white">Edit</a>
    <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="py-2 px-6 rounded-xl bg-red-500 text-white">Delete</a>

    <hr class="my-4">
    <h2 class="text-xl mb-6">Comments</h2>

    <div class="space-y-0.5">
        {% for comment in lead.comments.all %}
        <div class="bg-gray-50 p-6 rounded-xl">
            <p class="mb-2"><strong>{{ comment.created_by }} </strong> @ {{ comment.created_at }}</p>
            {{ comment.content }}
        </div>
        {% endfor %}
    </div>
    <form method="post" action="{% url 'leads:add_comment' lead.id %}">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-4 py-2 px-6 rounded-xl bg-blue-500 text-white">Submit</button>
    </form>

    <hr class="my-4">
    <h2 class="text-xl mb-6">Files</h2>
    <form method="post" action="{% url 'leads:add_file' lead.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{ fileform.as_p }}
        <button class="mt-4 py-2 px-6 rounded-xl bg-blue-500 text-white">Submit</button>
    </form>

    <div class="space-y-0.5">
        {% for file in lead.files.all %}
        <div class="bg-gray-50 p-6 rounded-xl">
            <p class="mb-2"><strong>{{ file.created_by }} </strong> @ {{ file.created_at }}</p>
            <a href="{{ file.file.url }}">Download</a>
        </div>
        {% endfor %}
    </div>


    <hr class="my-4">
    <a href="{% url 'leads:list' %}"class=" py-2 px-6 rounded-xl bg-gray-500 text-white">Back to leads</a>
</div>
{% endblock %}

crm_campaign/tealcrm/lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">{{ title }}</h1>

    {% if team.leads.count > 1 or title == 'Edit lead' %}
        <form method="post" action=".">
            {% csrf_token %}
    
            {{ form.as_p }}
    
            <button class="py-4 px-8 bg-blue-500 text-white rounded-xl">Submit</button>
        </form>
    {% else %}
        <div class=" mt-4 py-4 bg-red-400 rounded-xl text-white">
            Your team have has reached maximum number of leads. Your owner must upgrade your plan!
        </div>
    {% endif %}

</div>
{% endblock %}

crm_campaign/tealcrm/lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Leads {% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="mb-4 text-xl">Leads</h1>
    <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-blue-600 rounded-xl text-white">Add Lead</a>
    
    <div class="flex justify-between mb-4">
        <!-- Thanh tìm kiếm -->
        <form action="" method="get" class="flex items-center">
            <input type="text" name="q" placeholder="Search..." class=" mt-6 py-2 px-4 border-2 border-gray-300 rounded-l-lg focus:outline-none">
            <button type="submit" class="mt-6 py-2 px-6 bg-red-400 text-white rounded-r-lg border-2 ">Search</button>
        </form>
    </div>
    
    <!-- Phần hiển thị danh sách leads -->
    {% if object_list %}
        <!-- Các cột thông tin lead -->
        <div class="mt-5 flex justify-between">
            <!-- Các cột thông tin khác của lead -->
        </div>
    
        <!-- Vòng lặp để hiển thị danh sách lead -->
        {% for lead in object_list %}
            <div class="flex justify-between">
                <!-- Hiển thị thông tin từng lead -->
            </div>
        {% endfor %}
    {% endif %}


    {% if object_list %}
    <div class="mt-5 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Created at</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Email</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Phone</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Service</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Source</p>
  
    </div>
    {% for lead in object_list %}
        <div class="flex justify-between">
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">
             <a href="{% url 'leads:detail' lead.id %}" class="transition duration-500 hover:text-teal-500 transform hover:-translate-y-1 hover:scale-110 ...">{{ lead.name }}</a>   
            </p>
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ lead.created_at }}</p>
            <p class="lead-status {{ lead.status }} py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ lead.get_status_display }}</p>
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ lead.email }}</p>
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ lead.phone }}</p>
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ lead.product_line }}</p>
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ lead.lead_source }}</p>

        </div>
    {% endfor %}
{% else %}
    <p class="mt-6 px-2">There are no leads in the database yet...</p>
{% endif %}
<div class="pagination py-4 px-2 bg-gray-200 font-semibold w-full" style="display: flex; justify-content: center;margin-top: 20px;">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}" class="transition duration-500 hover:text-blue-500 transform hover:-translate-y-1 hover:scale-110 ...">Previous___</a>
        {% endif %}
    </span>
 
    <span class="current">
        Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
    </span>
     
    <span>
        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}" class="transition duration-500 hover:text-blue-500 transform hover:-translate-y-1 hover:scale-110 ...">___Next</a>
        {% endif %}
    </span>
</div>
</div>

<style>

.lead-status {
    padding: 5px; /* Điều chỉnh padding để tạo khoảng cách xung quanh chữ */
    display: inline; /* Để phần tử p hiển thị như một phần của văn bản */
    border-radius: 4px; /* Tạo viền cong cho background */
}

.unactioned {
    color: #13120f; /* Màu cho trạng thái "New" */
}

.new {
    color: #0758ed; /* Màu cho trạng thái "In Progress" */
}

.qualified {
    color: #18db35; /* Màu cho trạng thái "Completed" */
}
.contacted {
    color: #000000; /* Màu cho trạng thái "Completed" */
}
.unqualified {
    color: #eb2b2b; /* Màu cho trạng thái "Completed" */
}

</style>
{% endblock %}