crm_campaign/tealcrm/client/urls.py
from django.urls import path
from . import views


app_name = 'clients'

urlpatterns = [
    path('',views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('add/', views.clients_add, name='add'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>add-file/', views.clients_add_file, name='add_file'),
    path('export/', views.clients_export, name='export'),
]

crm_campaign/tealcrm/lead/urls.py
from django.urls import path


from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert', views.ConvertToClientView.as_view(), name='convert'),
    path('add/',views.LeadCreateView.as_view(), name = 'add'),
    path('<int:pk>/add-comment/',views.AddCommentView.as_view(), name= 'add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(),name = 'add_file') ,
    path('api', views.ListCreateLeadView.as_view()),
    path('api/<int:pk>', views.UpdateDeleteLeadView.as_view()),
] 

crm_campaign/tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index,about
from userprofile.views import signup
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from userprofile.form import LoginForm 

from django.conf import settings
from django.conf.urls.static import static




# Define your LoginView with a template_name attribute
class CustomLoginView(LoginView):
    template_name = 'userprofile/login.html'
class CustomLogoutView(LogoutView):
    template_name = ''

urlpatterns = [
    path('',index, name='index'),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/teams/',include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/',about, name='about'),
    path('log-in/', CustomLoginView.as_view(authentication_form =LoginForm), name='login'),
    path('log-out' ,CustomLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),    
    path("__debug__/", include("debug_toolbar.urls")),
    path('dynfilters/', include('dynfilters.urls')),    
    path('campaign/', include('campaigns.urls')),
    path('templates/', include('templates.urls', namespace='templates')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_campaign/tealcrm/client/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team
from product.models import Product
# Create your models here.


class Client(models.Model):

    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    phone = models.CharField(max_length=20, blank=True, null= True)
    product_line = models.ForeignKey(Product, related_name='clients', on_delete=models.CASCADE)
    company = models.CharField(max_length=100, blank=True, null= True)
    job = models.CharField(max_length=100, blank=True, null= True)

    
    class Meta:
        ordering = ('name',)

    def  __str__(self):
        return self.name

class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name= 'files', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='clientfiles')

    def __str__(self):
        return self.created_by.username
    

    
class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name= 'comments', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField( null=True,)

    def __str__(self):
        return self.created_by.username

crm_campaign/tealcrm/client/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client
from .form import AddClientForm, AddCommentForm, AddFileForm
from django.contrib import messages
from team.models import Team
from django.http import HttpResponse
import csv
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
@login_required

def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="clients.csv"'},
    )
    response.write(u'\ufeff'.encode('utf8'))
    writer = csv.writer(response)
    writer.writerow(["Client", "Description", "Create at", "Created by"])

    for client in clients:
        writer.writerow([client.name, client.description, client.created_at, client.created_by,])

    return response


@login_required
def clients_list(request):
    search_query = request.GET.get('q')
    clients_list = Client.objects.filter(created_by=request.user).order_by('-created_at')
    paginate_by = 15

    if search_query:
        clients_list = clients_list.filter(
            Q(name__icontains=search_query) |  # Thay 'name' bằng trường dữ liệu bạn muốn tìm kiếm
            Q(email__icontains=search_query) | # Thay 'email' bằng trường dữ liệu khác nếu cần
            Q(phone__icontains=search_query) | # Thay 'email' bằng trường dữ liệu khác nếu cần
            Q(product_line__name__icontains=search_query)  # Thay 'email' bằng trường dữ liệu khác nếu cần
            # Thêm các trường dữ liệu khác nếu muốn tìm kiếm ở nhiều trường
        )

    paginator = Paginator(clients_list, paginate_by)
  
    pageNumber = request.GET.get('page')
    try:
        clients = paginator.page(pageNumber)
    except PageNotAnInteger:
        clients = paginator.page(1)
    except EmptyPage:
        clients = paginator.page(paginator.num_pages)

    return render(request, 'client/clients_list.html',{
        'clients': clients,
        'search_query': search_query,# Trả về search_query để có thể hiển thị trên giao diện
    })


@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid(): 
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.client_id = pk 
            file.created_by = request.user
            file.save()
            
        return redirect('clients:detail', pk=pk)



@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    
    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()
            
            return redirect('clients:detail', pk=pk)
    else: 
        form = AddCommentForm()
        
    return render(request, 'client/clients_detail.html',{
            'client': client,
            'form': form,
            'fileform': AddFileForm(),
    })


@login_required
def clients_add(request):
    team = request.user.userprofile.active_team
    
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        
        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, 'The client was created.')

            return redirect('clients:list')
    else: 
        form = AddClientForm()
    return render(request, 'client/clients_add.html',{
        'form': form,
        'team': team
    })

@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    client.delete()
    messages.success(request, "The client was deleted.")

    return redirect('clients:list')

@login_required
def clients_edit(request,pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()
            messages.success(request, 'The changes was saved.')
            return redirect('clients:list')
    else:
        form = AddClientForm(instance=client)
    return render(request, 'client/clients_edit.html',{
        'form': form
        })

    

crm_campaign/tealcrm/client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %}Add client {% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">Add client</h1>

    {% if  team.clients.all|length > 1 %}
        <form method="post" action=".">
            {% csrf_token %}
    
            {{ form.as_p }}
    
            <button class="py-4 px-8 bg-blue-500 text-white rounded-xl">Submit</button>
        </form>
    {% else %}
        <div class="px-6 py-4 bg-red-400 rounded-xl text-white">
            Your team have has reached maximum number of clients. Your owner must upgrade your plan!
        </div>
    {% endif %}
</div>
{% endblock %}

crm_campaign/tealcrm/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
<style>
    .two-column-layout {
        display: grid;
        grid-template-columns: 1fr 1fr; /* Chia layout thành 2 cột bằng nhau */
        gap: 20px; /* Khoảng cách giữa các cột */

        
    }
    .two-column-layout div p {
    border-bottom: 1px solid #ccc; /* Dòng kẻ màu xám */
    padding-bottom: 8px; /* Khoảng cách từ chân dòng đến dòng kẻ */
    margin-bottom: 8px; /* Khoảng cách giữa các dòng */
}
</style>
<div class="py-6 px-6">
    <h1 class="text-xl">{{ client.name }}</h1>
    <div class="two-column-layout">
    <div>
    {% if client.description %}
        <p class="font-semibold">Description</p>
        <p>{{ client.description }}</p>
    {% endif %}
            <h1 class="font-semibold">Create at</h1>
            <p class="mb-2">{{client.created_at }}</p>
            <h1 class="font-semibold">Modified at</h1>
            <p class="mb-6">{{client.modified_at }}</p>
        </div>

        <div>
            <h1 class="font-semibold">Email</h1>
            <p class="mb-6">{{ client.email }}</p>
            <h1 class="font-semibold">Phone</h1>
            <p class="mb-6">{{ client.phone }}</p>
            <h1 class="font-semibold">Service</h1>
            <p class="mb-6">{{ client.product_line }}</p>
            <h1 class="font-semibold">Company</h1>
            <p class="mb-6">{{ client.company }}</p>
            <h1 class="font-semibold">Job</h1>
            <p class="mb-6">{{ client.job }}</p>
        </div>
           
    </div>
    
    <hr class="my-4">
    <a href="{% url 'clients:edit' client.id %}" class="py-2 px-6 rounded-xl bg-blue-500 text-white">Edit</a>
    <a id="delete-client" href="{% url 'clients:delete' client.id %}" class="py-2 px-6 rounded-xl bg-red-500 text-white">Delete</a>

    <!-- Script để hiển thị hộp thoại xác nhận -->
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('delete-client').addEventListener('click', function(event) {
            event.preventDefault();
            if (confirm('Are you sure you want to delete this client?')) {
                window.location.href = "{% url 'clients:delete' pk=client.pk %}";
            }
        });
    });
    </script>

    <hr class="my-4">
    <h2 class="text-xl mb-6">Comments</h2>
    <div class="space-y-0.5">
        {% for comment in client.comments.all %}
        <div class="bg-gray-50 p-6 rounded-xl">
            <p class="mb-2"><strong>{{ comment.created_by }} </strong> @ {{ comment.created_at }}</p>
            {{ comment.content }}
        </div>
        {% endfor %}
    </div>
    <form method="post" action="{% url 'clients:add_comment' client.id %}">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-4 py-2 px-6 rounded-xl bg-blue-500 text-white">Submit</button>
    </form>

    <hr class="my-4">
    <h2 class="text-xl mb-6">Files</h2>
    <form method="post" action="{% url 'clients:add_file' client.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{ fileform.as_p }}
        <button class="mt-4 py-2 px-6 rounded-xl bg-blue-500 text-white">Submit</button>
    </form>

    <div class="space-y-0.5">
        {% for file in client.files.all %}
        <div class="bg-gray-50 p-6 rounded-xl">
            <p class="mb-2"><strong>{{ file.created_by }} </strong> @ {{ file.created_at }}</p>
            <a href="{{ file.file.url }}">Download</a>
        </div>
        {% endfor %}
    </div>

    <hr class="my-4">
    <a href="{% url 'clients:list' %}"class=" py-2 px-6 rounded-xl bg-gray-500 text-white">Back to clients</a>
</div>
{% endblock %}

crm_campaign/tealcrm/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit client {% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">Edit client</h1>

    <form id="edit-client-form" method="post" action=".">
            {% csrf_token %}
    
            {{ form.as_p }}
    
            <button id="client-submit-edit" class="py-4 px-8 bg-blue-500 text-white rounded-xl">Submit</button>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    document.getElementById('client-submit-edit').addEventListener('click', function(event) {
                        event.preventDefault();
                        if (confirm('Are you sure you want to edit this client?')) {
                            document.getElementById('edit-client-form').submit();
                        }
                    });
                });
            </script>
        </form>
    </form>
</div>

{% endblock %}

crm_campaign/tealcrm/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %} Clients {% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="mb-4 text-xl">Clients</h1>
    <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-blue-600 rounded-xl text-white">Add client</a>
    <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 bg-blue-500 rounded-xl text-white">Export</a>
    <div class="flex justify-between mb-4">
        <!-- Thanh tìm kiếm -->
        <form action="" method="get" class="flex items-center">
            <input type="text" name="q" placeholder="Search..." class=" mt-6 py-2 px-4 border-2 border-gray-300 rounded-l-lg focus:outline-none">
            <button type="submit" class="mt-6 py-2 px-6 bg-red-400 text-white rounded-r-lg border-2 ">Search</button>
        </form>
    </div>
    
    <!-- Phần hiển thị danh sách leads -->
    {% if clients %}
        <!-- Các cột thông tin lead -->
        <div class="mt-5 flex justify-between">
            <!-- Các cột thông tin khác của lead -->
        </div>
    
        <!-- Vòng lặp để hiển thị danh sách lead -->
        {% for clients in clients %}
            <div class="flex justify-between">
                <!-- Hiển thị thông tin từng lead -->
            </div>
        {% endfor %}
    {% endif %}

    {% if clients %}
    <div class="mt-5 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Created at</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Email</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Phone</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Service</p>
    
    </div>
    {% for clients in clients %}
        <div class="flex justify-between">
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">
             <a href="{% url 'clients:detail' clients.id %}" class="transition duration-500 hover:text-teal-500 transform hover:-translate-y-1 hover:scale-110 ...">{{ clients.name }}</a>
             <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ clients.created_at }}</p>
             <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ clients.email }}</p>
             <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ clients.phone }}</p>
             <p class="py-2 px-2 w-full {% cycle 'bg-gray-50' '' %}">{{ clients.product_line }}</p>

            </p>
        </div>
    {% endfor %}
{% else %}
    <p class="mt-6 px-2">There are no clients in the database yet...</p>
{% endif %}
</div>
<div class="pagination py-4 px-2 bg-gray-200 font-semibold w-full" style="display: flex; justify-content: center;margin-top: 20px;">
    <span class="step-links">
        {% if clients.has_previous %}
            <a href="?page={{ clients.previous_page_number }}" class="transition duration-500 hover:text-blue-500 transform hover:-translate-y-1 hover:scale-110 ..."><strong>Previous----</strong></a>
        {% endif %}
    </span>
 
    <span class="current">
        Page {{ clients.number }} of {{ clients.paginator.num_pages }}.
    </span>
     
    <span>
        {% if clients.has_next %}
            <a href="?page={{ clients.next_page_number }}" class="transition duration-500 hover:text-blue-500 transform hover:-translate-y-1 hover:scale-110 ..."><strong>----Next</strong></a>
        {% endif %}
    </span>
</div>
</div>

{% endblock %}