crm_campaign/tealcrm/client/urls.py
from django.urls import path
from . import views


app_name = 'clients'

urlpatterns = [
    path('',views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('add/', views.clients_add, name='add'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>add-file/', views.clients_add_file, name='add_file'),
    path('export/', views.clients_export, name='export'),
]

crm_campaign/tealcrm/dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name= 'index'),
]

crm_campaign/tealcrm/lead/urls.py
from django.urls import path


from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert', views.ConvertToClientView.as_view(), name='convert'),
    path('add/',views.LeadCreateView.as_view(), name = 'add'),
    path('<int:pk>/add-comment/',views.AddCommentView.as_view(), name= 'add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(),name = 'add_file') ,
    path('api', views.ListCreateLeadView.as_view()),
    path('api/<int:pk>', views.UpdateDeleteLeadView.as_view()),
] 

crm_campaign/tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index,about
from userprofile.views import signup
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

from userprofile.form import LoginForm 

from django.conf import settings
from django.conf.urls.static import static




# Define your LoginView with a template_name attribute
class CustomLoginView(LoginView):
    template_name = 'userprofile/login.html'
class CustomLogoutView(LogoutView):
    template_name = ''

urlpatterns = [
    path('',index, name='index'),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/teams/',include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/',about, name='about'),
    path('log-in/', CustomLoginView.as_view(authentication_form =LoginForm), name='login'),
    path('log-out' ,CustomLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),    
    path("__debug__/", include("debug_toolbar.urls")),
    path('dynfilters/', include('dynfilters.urls')),    
    path('campaign/', include('campaigns.urls')),
    path('templates/', include('templates.urls', namespace='templates')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_campaign/tealcrm/team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/', views.detail, name='detail'),
    path('', views.teams_list, name='list'),
    path('<int:pk>/activate', views.teams_activate, name='activate'),
]

crm_campaign/tealcrm/userprofile/urls.py
from django.urls import path

from. import views
from .form import SignupForm
app_name = 'userprofile'


urlpatterns = [
    path('myaccount',views.myaccount,name='myaccount' ),
    path('sign-up/',views.signup, name='signup'),
]

crm_campaign/tealcrm/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'core/index.html')
def about(request):
    return render(request, 'core/about.html')

crm_campaign/tealcrm/core/templates/core/partials/footer.html
<!-- <footer class="py-6 text-center bg-gray-200">
    <p class="text-xs text-gray-700">Coppyright (c) 2023 - Teal CRM</p>
</footer> -->

crm_campaign/tealcrm/core/templates/core/partials/nav.html
<nav class="py-6 px-6 flex justify-between bg-gray-200">
    <a href="/" class="text-blue-700">CRM-Driven Campaign</a>
        <div class="space-x-4">
            <a href="{% url 'about' %}" class="text-blue-700">About</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'team:detail' active_team.id %}" class="text-blue-700">{{ active_team.name }}</a>

            <a href="{% url 'dashboard:index' %}" class="py-4 px-6 bg-blue-500 rounded-xl text-white">Dashboard</a>
            <a href="{% url 'leads:list' %}" class="py-4 px-6 bg-blue-500 rounded-xl text-white">Leads</a>
            <a href="{% url 'clients:list' %}" class="py-4 px-6 bg-blue-500 rounded-xl text-white">Clients</a>
            <a href="{% url 'campaigns' %}" class="py-4 px-6 bg-blue-500 rounded-xl text-white">Campaign</a>
            <a href="{% url 'userprofile:myaccount' %}" class="py-4 px-6 bg-blue-500 rounded-xl text-white">My account</a>
            {% else %}
            <a href="{% url 'login' %}" class="py-4 px-6 bg-blue-600 rounded-xl text-white">Login</a>
            <a href="{% url 'userprofile:signup' %}" class="py-4 px-6 bg-blue-400 rounded-xl text-white">Sign up</a>
            {% endif %}
        </div>
</nav>